algoritmo "EquacaoSegundoGrau"
var
   a, b, c, delta: real
inicio
      EscrevaL("Delta = b²-4.a.c")
      EscrevaL("------------------------")
      Escreva("Digite o valor de a: ")
      leia(a)
      Escreva("Digite o valor de b: ")
      leia(b)
      Escreva("Digite o valor de c: ")
      leia(c)
      EscrevaL("Delta =", b,"²-4.",a,".",c)
      delta <- b^2-4*a*c
      EscrevaL("------------------------")
      Escreva("Delta = ", delta)

      
      
fimalgoritmo
