algoritmo "ContagemInteligente"

var
   comeco, fim, cont: inteiro
inicio
      EscrevaL("CONTAGEM INTELIGENTE")
      EscrevaL("---------------------")

      Escreva("Inicio: ")
      leia(comeco)

      Escreva("Fim: ")
      leia(fim)

      EscrevaL("---------------------")
      EscrevaL("C O N T A N D O")
      EscrevaL("---------------------")

      Enquanto (comeco <= fim) faca
      Escreva(comeco,"...")
      cont <- comeco + 1
      se
      FimSe
      FimEnquanto
fimalgoritmo
